Task22 6
Nebres/MyAPP pull request #21
Opened 2018-10-21 15:12 UTC by Nebres

2018-10-21 15:13 UTC, Nebres commented on src/main/resources/zadanie22_6.sql
> +create index READERS_FIRSTANAME_INDEX ON readers(LASTNAME);
Błąd ze zdublowaną nazwą poprawiony w kolejnym commicie

2018-10-21 21:20 UTC, mps4dev requested changes
:-1:

2018-10-21 21:20 UTC, mps4dev commented on src/main/resources/zadanie22_6.sql
> +explain select count(*) from readers where FIRSTNAME between 'g' and 'r';
skąd to between 'g' and 'r'?

2018-10-21 21:20 UTC, mps4dev commented on src/main/resources/zadanie22_6.sql
> +create index READERS_FIRSTANAME_INDEX ON readers(LASTNAME);
create index READERS_FIRSTNAME_IDX ON readers(FIRSTNAME, LASTNAME);

2018-10-27 20:02 UTC, mps4dev approved these changes
:+1:

2019-02-11 12:33 UTC, merged